### ISSUE TITLE
Unclear, does this only install on ARM machines ?

### ISSUE THREAD

**Issue by EMCP** [ComputerEnchiladas/mahrio-raspbian#1]
tried install on OSX machine and getting errors that seem consistent with being unable to compile something

```
npm WARN EPACKAGEJSON mahrio-raspbian@1.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/EMCP/.nvm/versions/node/v5.0.0/bin/node" "/Users/EMCP/.nvm/versions/node/v5.

0.0/bin/npm" "i"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! raspi-gpio@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raspi-gpio@2.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the raspi-gpio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raspi-gpio
npm ERR! There is likely additional logging output above.
```

**Comment by EMCP** [comment]
needed to manually install wiringPi

`sudo apt-get install wiringPi` ,

then `npm i` could complete on my Pi

**Comment by EMCP** [comment]
now when i run `node server/index.js` I get an error

```
pi@raspberrypi:~/Dev/ComputerEnchiladas/mahrio-raspbian $ node server/index.js
Running Development!
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn irw ENOENT
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by EMCP** [comment]
attempted to modify the `.env` file to my IP.. still erroring

now I'm creating the folder `/media/pi/EMCPMINI`

still erroring

**Comment by EMCP** [comment]
retrying with latest `node v6.x.x`

**Comment by JesusGuerrero** [comment]
Arm7... I've found out the pi you gave me was an arm6, and two others I picked up have been arm7. Arm7 is needed to install node 6.x

Sent from my iPhone

On Oct 2, 2016, at 12:19 PM, Erik <notifications@github.com<mailto:notifications@github.com>> wrote:

retrying with latest node v6.x.x

##

**Comment by JesusGuerrero** [comment]
irw error is because you need to configure the linx infrared remote control (lirc) on raspbian. I forgot where I found the instruction to set this up, but I do have a test file to check the remote was configured properly. https://github.com/ComputerEnchiladas/mahrio-ir-remote-receiver

**Comment by JesusGuerrero** [comment]
if you disable the configuration for lirc within server/config you should be able to successfully launch server while bypassing lirc just to see server work. You don't need infrared remote to use the media site

**Comment by EMCP** [comment]
good to know, I have node `v6` installed on this armv6 pi so... I'll keep trying by disabling the lirc

**Comment by EMCP** [comment]
got more errors.. closing this ticket since I understand now that arm `v6` isn't supported

```
Running Development!
remote events.Emitter assigned.
/home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/epoll/build/epoll.node
 → /home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/epoll/build/Debug/epoll.node
 → /home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/epoll/build/Release/epoll.node
 → /home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/epoll/out/Debug/epoll.node
 → /home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/epoll/Debug/epoll.node
 → /home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/epoll/out/Release/epoll.node
 → /home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/epoll/Release/epoll.node
 → /home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/epoll/build/default/epoll.node
 → /home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/epoll/compiled/5.12.0/linux/arm/epoll.node
    at bindings (/home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/epoll/epoll.js:1:99)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/Dev/ComputerEnchiladas/mahrio-raspbian/node_modules/onoff/onoff.js:4:11)
    at Module._compile (module.js:413:34)
```
